config/routes.rb
Rails.application.routes.draw do
  resources :lives
  
  resources :cats do
    resources :lives
  end

  get 'sessions/new'
  get 'logout' => 'sessions#destroy'

  resource :user
  get 'users/new'

  root 'sessions#new'
  resource :session

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  has_many :lives
end

app/models/life.rb
class Life < ApplicationRecord
  belongs_to :cat
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :cats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user

    #caching
    #memoization
    @current_user ||=  User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def require_logged_in
    if current_user
      true
    else
      redirect_to root_path
    end
    #redirect_to root_path unless current_user
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :require_logged_in

  # GET /cats
  # GET /cats.json
  def index
    # @cats = Cat.all
    @cats = current_user.cats
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    # @cat = Cat.new
    @cat = current_user.cats.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    # @cat = Cat.new(cat_params)
    @cat = current_user.cats.new(cat_params)
    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_cat
    # @cat = Cat.find(params[:id])
    @cat = current_user.cats.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cat_params
    params.require(:cat).permit(:name, :user_id)
  end

end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  before_action :set_life , only: [:show, :edit, :update, :destroy]
  before_action :set_cat, only:[:index, :new, :create, :update]

  # GET /lives
  # GET /lives.json
  def index
    @lives = @cat.lives
  end

  # GET /lives/1
  # GET /lives/1.json
  def show
  end

  # GET /lives/new
  def new
    @life = @cat.lives.new
    # @cat = Cat.find(params[:cat_id])
  end

  # GET /lives/1/edit
  def edit
  end

  # POST /lives
  # POST /lives.json
  def create
    # @cat = Cat.find(params[:cat_id])
    @life = @cat.lives.new(life_params)
    # @life.cat = @cat

    respond_to do |format|
      if @life.save
        format.html { redirect_to @life, notice: 'Life was successfully created.' }
        format.json { render :show, status: :created, location: @life }
      else
        format.html { render :new }
        format.json { render json: @life.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lives/1
  # PATCH/PUT /lives/1.json
  def update
    respond_to do |format|
      if @life.update(life_params)
        format.html { redirect_to @life, notice: 'Life was successfully updated.' }
        format.json { render :show, status: :ok, location: @life }
      else
        format.html { render :edit }
        format.json { render json: @life.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lives/1
  # DELETE /lives/1.json
  def destroy
    @life.destroy
    respond_to do |format|
      format.html { redirect_to lives_url, notice: 'Life was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_life
      @life = Life.find(params[:id])
    end

    def set_cat
      @cat = current_user.cats.find(params[:cat_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def life_params
      params.require(:life).permit(:number, :cat_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def  create
    @user = User.find_by(username: params[:username])
    if @user and @user.authenticate(params[:password])

      session[:user_id] = @user.id
      redirect_to cats_path
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      redirect_to root_path, notice: 'Created user'
    else
      render :new
    end
  end

private
def user_params
  params.require(:user).permit(:username, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/lives_helper.rb
module LivesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true) do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cat_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Show', @cat %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.user %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'form', cat: @cat %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>



<%= link_to 'Edit', edit_cat_path(@cat) %> |
<%= link_to 'Back', cats_path %>


<h2>Lives</h2>
<ul>
  <% @cat.lives.each do |life| %>
  <li><%= link_to life.number, life %></li>
  <% end %>
</ul>

<p>
<%= link_to 'New Life', new_cat_life_path(@cat) %>

</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretResources</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lives/_form.html.erb
<%= form_with(model: [cat , life], local: true) do |form| %>
  <% if life.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(life.errors.count, "error") %> prohibited this life from being saved:</h2>

      <ul>
      <% life.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :life_number %>
  </div>

  <!-- <div class="field">
    <%= form.label :cat_id %>
    <%= form.text_field :cat_id, id: :life_cat_id %>
  </div> -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lives/edit.html.erb
<h1>Editing Life</h1>

<%= render 'form', life: @life %>

<%= link_to 'Show', @life %> |
<%= link_to 'Back', lives_path %>

app/views/lives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lives</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Cat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lives.each do |life| %>
      <tr>
        <td><%= life.number %></td>
        <td><%= life.cat %></td>
        <td><%= link_to 'Show', life %></td>
        <td><%= link_to 'Edit', edit_life_path(life) %></td>
        <td><%= link_to 'Destroy', life, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Life', new_life_path %>

app/views/lives/new.html.erb
<h1>New Life</h1>

<%= render 'form', life: @life, cat: @cat %>

<%= link_to 'Back', @cat %>

app/views/lives/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @life.number %>
</p>

<p>
  <strong>Cat:</strong>
  <%= @life.cat.name %>
</p>

<%= link_to 'Edit', edit_life_path(@life) %> |
<%= link_to 'Back', @life.cat %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with(model: @user, url: user_path(@user)) do |f|%>
<p>
<%= f.label :username %>
<%= f.text_field :username %>
</p>
<p>
<%= f.label  :password %>
<%= f.password_field :password %>
</p>

<p>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
</p>
<%= f.submit %>
<% end %>